# Generated by Django 6.0.5 on 2026-05-21 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'ادمین'), ('manager', 'مدیر'), ('member', 'عضو'), ('viewer', 'بیننده')], default='viewer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عضویت',
                'verbose_name_plural': 'عضویت',
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('plan', models.CharField(choices=[('free', 'رایگان'), ('pro', 'پرو'), ('enterprise', 'شرکتی')], default='free', max_length=20)),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان',
                'db_table': 'organizations',
            },
        ),
    ]
